---
Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
